import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

import { AbstractModel } from './abstract';

@table(process.env.DYNAMODB_TABLE_DEVICES)
export class Device extends AbstractModel {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  name: string;

  @attribute()
  locationId: string;
}
