import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

import { AbstractModel } from './abstract';

@table(process.env.DYNAMODB_TABLE_LOCATIONS)
export class Location extends AbstractModel {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  name: string;

  @attribute()
  latitude: number;

  @attribute()
  longitude: number;

  @attribute()
  email: string;
}
