import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

import { AbstractModel } from './abstract';

@table(process.env.DYNAMODB_TABLE_USERS)
export class User extends AbstractModel {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  firstName: string;

  @attribute()
  lastName: string;

  @attribute()
  email: string;
}
